artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://github.com/Durgeshsingh12712/Data-All/raw/refs/heads/main/email.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  raw_data_path: artifacts/data_ingestion/email.csv

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion
  status_file: artifacts/data_validation/status.txt
  required_columns: ["Category"]
