artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://github.com/Durgeshsingh12712/Data-All/raw/refs/heads/main/email.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  raw_data_path: artifacts/data_ingestion/email.csv

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion
  status_file: artifacts/data_validation/status.txt
  required_columns: ["Category"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/email.csv
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  vectorizer_path: artifacts/data_transformation/vectorizer.pkl
  test_size: 0.2
  random_state: 42

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  vectorizer_path: artifacts/data_transformation/vectorizer.pkl
  model_name: model.pkl
  target_column: Category

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl
  vectorizer_path: artifacts/data_transformation/vectorizer.pkl
  metric_file_name: metrics.json                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  